### ISSUE TITLE
Database contains 0 docs and 0 tasks

### ISSUE THREAD

**Issue by CodingFan72** [MDQL/vscode-extension#1]
Hi,

I tried the Markdown Data View Extension but I didn't get any search results.

I created a test repo on my PC and created a demo file similar to yours:

    # Markdown DataViews Demo
    
    - [ ] Buy bananas  
    - [ ] Fix bug in Code  
    - [ ] Watch SciFi movie
    
    ```mdql
    TASKLIST text FROM tasks
    ```

This is the preview of the file:

![image](https://github.com/MDQL/vscode-extension/assets/76176989/67d8adc7-51c5-47f2-aa18-897c41ae1478)

In the OUTPUT panel I see 

![image](https://github.com/MDQL/vscode-extension/assets/76176989/bda72697-9650-4af5-b425-eb56c9b7d381)

What did I wrong?

Greetings

**Comment by gorootde** [comment]
Thanks for reporting this bug. This is fixed in v0.0.9 which was just published and will be available in VSCode shortly.
